"use client";
import DarkBg from "@/components/UI/DarkBg";
import { useEffect, useRef } from "react";
import gsap from "gsap";
import ScrollTrigger from "gsap/ScrollTrigger";
import "@/assets/styles/privacy-policy.scss";
import Image from "next/image";
// import circle_1 from "@/assets/img/badge/circle-1.svg";
// import circle_2 from "@/assets/img/badge/circle-2.svg";
import circle_1 from "@/assets/img/ellipse-grid.svg";
import circle_2 from "@/assets/img/ellipse-grid.svg";
gsap.registerPlugin(ScrollTrigger);
export default function PrivacyPolicy() {
  const titleRef = useRef(null);

  useEffect(() => {
    gsap.fromTo(
      titleRef.current,
      { autoAlpha: 0, y: 20 },
      {
        autoAlpha: 1,
        y: 0,
        duration: 1,
        ease: "power1.out",
        scrollTrigger: {
          trigger: titleRef.current,
          start: "top 70%",
        },
      }
    );
  }, []);
  return (
    <div>
      <DarkBg>
        <div className="container bottom-sec ">
          <h2 className="bottom-sec__title" ref={titleRef}>
            Privacy Policy
          </h2>
          <div className="bottom-sec__text-container"></div>
        </div>

        <Image className="bottom-sec__circle-1" src={circle_1} />
        <Image className="bottom-sec__circle-2" src={circle_2} />
      </DarkBg>
      <div className="policy-text">
        <p style={{ color: "black", fontWeight: 500, fontSize: "16px" }}>
          Effective Date: September 19, 2024
        </p>
        <ul style={{ paddingLeft: "0px" }}>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>1 . Introduction</p>
            <p style={{ color: "#334663" }}>Welcome to Stingrai Inc.</p>
            <p style={{ color: "#334663" }}>
              Stingrai Inc. (“we”, “us”, or “our”) operates https://stingrai.io (hereinafter
              referred to as “Service”). This Privacy Policy governs your visit to
              https://stingrai.io and explains how we collect, safeguard, and disclose information
              that results from your use of our Service. We use your data to provide and improve
              Service. By using our Service, you agree to the collection and use of information in
              accordance with this policy. Unless otherwise defined in this Privacy Policy, terms
              used in this Privacy Policy have the same meanings as in our Terms and Conditions.
            </p>
            <p style={{ color: "#334663" }}>
              Our Terms and Conditions (“Terms”) govern all use of our Service, and together with
              this  Privacy Policy, form your agreement with us.
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>2 . Definitions</p>
            <p style={{ color: "#334663" }}>
              <span style={{ color: "#334663", fontWeight: 700 }}>- SERVICE:</span> Refers to the
              https://stingrai.io website operated by Stingrai Inc.
            </p>
            <p style={{ color: "#334663" }}>
              <span style={{ color: "#334663", fontWeight: 700 }}>- PERSONAL DATA:</span> Data about
              a living individual who can be identified from that data (or  from that and other
              information in our possession or likely to come into our possession).
            </p>
            <p style={{ color: "#334663" }}>
              <span style={{ color: "#334663", fontWeight: 700 }}>- USAGE DATA:</span> Data
              collected automatically, either generated by the use of Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </p>
            <p style={{ color: "#334663" }}>
              <span style={{ color: "#334663", fontWeight: 700 }}>- COOKIES:</span> Small files
              stored on your device (computer or mobile device).
            </p>
            <p style={{ color: "#334663" }}>
              <span style={{ color: "#334663", fontWeight: 700 }}>- DATA CONTROLLER:</span> A person
              or entity that determines the purposes for which and the manner in which personal data
              are processed. For the purpose of this Privacy Policy, Stingrai Inc. is the Data
              Controller.
            </p>
            <p style={{ color: "#334663" }}>
              <span style={{ color: "#334663", fontWeight: 700 }}>
                - DATA PROCESSORS (OR SERVICE PROVIDERS):
              </span>{" "}
              Natural or legal persons who process the data on behalf of the Data Controller.
            </p>
            <p style={{ color: "#334663" }}>
              <span style={{ color: "#334663", fontWeight: 700 }}>- DATA SUBJECT:</span> A living
              individual who is the subject of Personal Data.
            </p>
            <p style={{ color: "#334663" }}>
              <span style={{ color: "#334663", fontWeight: 700 }}>- THE USER:</span> The individual
              using our Service, corresponding to the Data Subject.
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>3 . Information Collection and Use</p>
            <p style={{ color: "#334663" }}>
              We collect several types of information for various purposes to provide and improve
              our Service.
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>4 . Types of Data Collected</p>
            <p style={{ color: "#334663", fontWeight: 700 }}>Personal Data</p>
            <p style={{ color: "#334663" }}>
              We may ask you to provide certain personally identifiable information that can be used
              to contact or identify you (“Personal Data”). Personal Data may include, but is not
              limited to:
            </p>
            <p style={{ color: "#334663" }}>- Email address</p>
            <p style={{ color: "#334663" }}>- First and last name</p>
            <p style={{ color: "#334663" }}>- Phone number</p>
            <p style={{ color: "#334663" }}>- Address, Province, Postal code, City</p>
            <p style={{ color: "#334663" }}>- Cookies and Usage Data</p>
            <p style={{ color: "#334663" }}>
              We may use your Personal Data to contact you with newsletters, marketing, or
              promotional  materials. You may opt-out of receiving these communications by
              contacting us at <span style={{ color: "black" }}>info@stingrai.io</span>
            </p>
            <p style={{ color: "#334663", fontWeight: 700 }}>Usage Data</p>
            <p style={{ color: "#334663" }}>
              We may collect information such as your computer's IP address, browser type, browser
              version, pages visited, time and date of visit, and other diagnostic data.
            </p>
            <p style={{ color: "#334663", fontWeight: 700 }}>Cookies</p>
            <p style={{ color: "#334663" }}>
              We use Cookies and similar tracking technologies to track activity on our Service and
              hold  certain information
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>5 . Use of Data</p>
            <p style={{ color: "#334663" }}>
              Stingrai Inc. uses the collected data for various purposes:
            </p>
            <p style={{ color: "#334663" }}>- To provide and maintain our Service</p>
            <p style={{ color: "#334663" }}>- To notify you about changes to our Service</p>
            <p style={{ color: "#334663" }}>- To allow you to participatein interactive features</p>
            <p style={{ color: "#334663" }}>- To provide customer support</p>
            <p style={{ color: "#334663" }}>
              - To gather analysis or valuable information to improve our Service
            </p>
            <p style={{ color: "#334663" }}>- To detect, prevent, and address technical issues</p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>6 . Retention of Data</p>
            <p style={{ color: "#334663" }}>
              We retain your Personal Data only as long as necessary to fulfill the purposes for
              which it was collected and to comply with legal obligations.
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>7 . Transfer of Data</p>
            <p style={{ color: "#334663" }}>
              Your information may be transferred to and maintained on computers located outside of
              your province or country. Your submission of information represents your agreement to
              that transfer.
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>8 . Disclosure of Data</p>
            <p style={{ color: "#334663" }}>
              We may disclose your Personal Data under the following conditions:
            </p>
            <p style={{ color: "#334663" }}>
              {" "}
              - If required by law or in response to legal requests
            </p>
            <p style={{ color: "#334663" }}>
              {" "}
              - In connection with business transactions such as mergers or acquisitions
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>9 . Security of Data</p>
            <p style={{ color: "#334663" }}>
              We take reasonable precautions to protect your data, but no method of transmission
              over the internet or electronic storage is 100% secure.
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>
              10 . Your Data Protection Rights (PIPEDA & Ontario Laws)
            </p>
            <p style={{ color: "#334663" }}>
              As a Canadian resident, particularly under Ontario laws and the Personal Information
              Protection
            </p>
            <p style={{ color: "#334663" }}>
              and Electronic Documents Act (PIPEDA), you have the following rights:
            </p>
            <p style={{ color: "#334663" }}>- Access to your personal data</p>
            <p style={{ color: "#334663" }}>- Correction or deletion of your personal data</p>
            <p style={{ color: "#334663" }}>- Limitation of processing</p>
            <p style={{ color: "#334663" }}>
              - Withdrawal of consent to the use of your personal data
            </p>
            <p style={{ color: "#334663" }}>
              To exercise your rights, please contact us at{" "}
              <span style={{ color: "black" }}>info@stingrai.io</span>
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>11 . Service Providers</p>
            <p style={{ color: "#334663" }}>
              We may employ third-party companies to provide services on our behalf. These third
              parties  have access to your Personal Data only to perform tasks on our behalf and are
              required not to disclose or use it for any other purpose.
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>12 . Children's Privacy</p>
            <p style={{ color: "#334663" }}>
              Our Service does not address anyone under the age of 18. We do not knowingly collect
               personal information from children under 18.
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>13 . Changes to This Privacy Policy</p>
            <p style={{ color: "#334663" }}>
              We may update our Privacy Policy from time to time. Any changes will be posted on this
              page  with an updated effective date.
            </p>
          </li>
          <li style={{ listStyleType: "none" }}>
            <p style={{ color: "black", fontSize: "22px" }}>14 . Contact Us</p>
            <p style={{ color: "#334663" }}>
              If you have any questions about this Privacy Policy, please contact us:
            </p>
            <p style={{ color: "#334663" }}>
              By email: <span style={{ color: "black" }}>info@stingrai.io</span>
            </p>
          </li>
        </ul>
      </div>
    </div>
  );
}
